config/routes.rb
Rails.application.routes.draw do

  devise_for :players, controllers: {registrations: "registrations"}, skip: [:registrations]
  resources :news
  resources :absences
  #get "players/calendar" => "players#calendar"
  resources :players
  #get "matches/calendar" => "matches#calendar"
  resources :matches
  
  resources :calendar
  
  resources :tables
  
  resources :passwords
  
  root :to => 'calendar#index'
  
  get "/passwords" => "passwords#index"
  
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_player!
  before_action :insure_is_captain, except: [:index]
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all.sort_by(&:start_time)
   
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:start_time, :title, :content)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<html class = "form-group", align= "center">
  <%= form_for(@news) do |f| %>
    <% if @news.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>
  
        <ul>
        <% @news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field", align: "center">
      <%= f.label :start_time %><br>
      <%= f.datetime_select :start_time %>
    </div>
    
    <div class="field", align: "center">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control", size: "70x10", placeholder: "Title" %>
    </div>
    <div class="field", align: "center">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "form-control", cols: 70, rows: 10, placeholder: "Description" %>
      <%#= f.text_field :content, size: "70x60"%>
    </div>
    <br>
    
    <div class="actions", align: "center">
       <%= button_tag(type: 'submit', class: "btn btn-success") do %>
         Submit
        <% end %>
        <btn><%= link_to 'Back', news_index_path, class: "btn btn-success" %></btn>
    </div>
  
  <% end %>
</html>

app/views/news/edit.html.erb
<div class="panel panel-success">
  <h1 class="panel-heading text-center">Editing News</h1>
    <div class="panel-body">
  
      <%= render 'form' %>
    
    </div>
</div>
<%#= link_to 'Show', @news %> |
<%#= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class ="text-center">Listing News</h1>

<% @news.each do |news| %>
  <thead>
    <tr>
      <div class = "panel panel-success">
        <h2 class = "panel-heading"><%= news.title %></h2>
        <div class = "panel-body">
          <h4>Date: <%= news.start_time.strftime("%d/%m/%Y") %></h4>
          <h4>Time: <%= news.start_time.strftime("%I:%M%p") %></h4>
          <h4>Description</h4>
          
          <td><%= simple_format(news.content) %></td>
          </br>
          <% if current_player.captain %>
            <td><%= link_to 'Show', news, class: "btn btn-default btn-success btn-xs" %></td>
            <td><%= link_to 'Edit', edit_news_path(news), class: "btn btn-default btn-success btn-xs" %></td>
            <td><%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-success btn-xs" %></td>
            <th colspan="3"></th>
          <% end %>
          
          <br/>
        </div>
      </div>
    </tr>
  </thead>
  </br>
<% end %>

<br>

<% if current_player.captain %>
  <btn><%= link_to 'New Item', new_news_path, class: "btn btn-default btn-success" %></btn>
<% end %>

app/views/news/new.html.erb
<div class="panel panel-success">
  <h2 class="panel-heading text-center">New Event</h2>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <div class="panel-heading text-center">Viewing News</div>
  <div class="panel-body">
  

    <p>
      <strong>Start time:</strong>
      <%= @news.start_time %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @news.title %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @news.content %>
    </p>

    <btn><%= link_to 'Edit', edit_news_path(@news), class: "btn btn-default btn-success" %></btn>
    <btn><%= link_to 'Back', news_index_path, class: "btn btn-default btn-success" %></btn>

  </div>
</div>