config/routes.rb
Rails.application.routes.draw do

  devise_for :players, controllers: {registrations: "registrations"}, skip: [:registrations]
  resources :news
  resources :absences
  #get "players/calendar" => "players#calendar"
  resources :players
  #get "matches/calendar" => "matches#calendar"
  resources :matches
  
  resources :calendar
  
  resources :tables
  
  resources :passwords
  
  root :to => 'calendar#index'
  
  get "/passwords" => "passwords#index"
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  
  has_and_belongs_to_many :matches    #represents has and belongs to many relationship, with a join table involved
  has_many :absences, :dependent => :destroy # player has many absences, depedant means if destoryed absence is destroyed

  devise :database_authenticatable, :registerable,    
         :recoverable, :rememberable, :trackable, :validatable  
    
  def generate_password
    self.password = "12345678"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_player!  #checks weather player is signed in
  before_action :insure_is_captain, except: [:index]    #ensures only captain can see rest of pages except the index page
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end
  

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    @player.generate_password
    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :team, :email, :mobile, :captain, :match_ids => [])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field", align = "center">
    <%= f.label :name %>:<br>
    <%= f.text_field :name, class: "form-control-small", placeholder: "Name"  %>
  </div>
  <div class="field", align = "center">
    <%= f.label :team %>:<br>
    <%= f.select :team, [['1sts',1],['2nds',2],['3rds', 3],['4ths', 4]] %>
  </div>
  <br>
  <div class="field", align = "center">
    <%= f.label :email %>:<br>
    <%= f.text_field :email, class: "form-control-small", placeholder: "Email" %>
  </div>
  <div class="field", align = "center">
    <%= f.label :mobile %>:<br>
    <%= f.text_field :mobile, class: "form-control-small", placeholder: "Mobile" %>
  </div>
  <div class="field", align = "center">
    <%= f.label :captain %>:<br>
    <%= f.radio_button :captain, true %> - Is a captain </br>
    <%= f.radio_button :captain, false %> - Not a Captain
  </div>
  
  <br>
  <div class="actions", align = "center">
    <%= button_tag(type: 'submit', class: "btn btn-success") do %>
     Submit
    <% end %>
    <btn ><%= link_to 'Back', players_path, class: "btn btn-success" %></btn>
    
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="panel panel-success">
  <h1 class="panel-heading text-center">Editing Player</h1>
    <div class="panel-body">
  
      <%= render 'form' %>
    
    </div>
</div>

<%#= link_to 'Show', @player %> |
<%#= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <h2 class="panel-heading text-center">Listing DUHC Players</h2>
  <div class="panel-body">

    <table class = "table table-striped table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Team</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Captain</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.name %></td>
            <td><%= player.team %></td>
            <td><%= player.email %></td>
            <td><%= player.mobile %></td>
            <td>
              <% if player.captain %>
                <t>Yes</t>
              <% else %>
                <t>No</t>
              <% end %>
            </td>
            <% if current_player.captain %>
              <td><%= link_to 'View', player, class: "btn btn-default btn-success btn-xs" %></td>
              <td><%= link_to 'Edit', edit_player_path(player), class: "btn btn-default btn-success btn-xs" %></td>
              <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-success btn-xs" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<% if current_player.captain %>
  <btn><%= link_to 'New Player', new_player_path, class: "btn btn-default btn-success" %></btn>
<% end %>

app/views/players/new.html.erb
<div class="panel panel-success">
  <h2 class="panel-heading text-center">New Player</h2>
  <div class="panel-body">
    
  

        <%= render 'form' %>

    </div>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-success">
  <h1 class="panel-heading text-center">Viewing <%= @player.name %></h1>
  <div class="panel-body">

    <p>
      <strong>Team:</strong>
      <%= @player.team  %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @player.email %>
    </p>

    <p>
      <strong>Mobile:</strong>
      <%= @player.mobile %>
    </p>

    <p>
      <strong>Captain:</strong>
      <%= @player.captain %>
    </p>

    <btn><%= link_to 'Edit', edit_player_path(@player), class: "btn btn-success" %></btn>
    <btn><%= link_to 'Back', players_path, class: "btn btn-success" %></btn>

</div>
</div>