config/routes.rb
Rails.application.routes.draw do

  devise_for :players, controllers: {registrations: "registrations"}, skip: [:registrations]
  resources :news
  resources :absences
  #get "players/calendar" => "players#calendar"
  resources :players
  #get "matches/calendar" => "matches#calendar"
  resources :matches
  
  resources :calendar
  
  resources :tables
  
  resources :passwords
  
  root :to => 'calendar#index'
  
  get "/passwords" => "passwords#index"
  
end

app/models/match.rb
class Match < ActiveRecord::Base
    has_and_belongs_to_many :players
    
    #def start_time
     #   self.match.time    ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    #end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_player!
  before_action :insure_is_captain, except: [:index, :show]
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  def index
    @matches = Match.all
  end

  def show
    
  end

  # GET /matches/new
  def new
    @match = Match.new
    date = params[:start_time]
    if date
      @date = DateTime.new date["{}(1i)"].to_i, date["{}(2i)"].to_i, date["{}(3i)"].to_i
      @match.start_time = @date
      @absent_players = Absence.where("absent_from <= ? AND absent_until >= ?", @date, @date).map(&:player)
      absent_players_ids = @absent_players.to_a.compact.map(&:id) || []
      @available_players = absent_players_ids == [] ? Player.all : Player.where("id NOT IN (?)", absent_players_ids)
      @selected_players = @match.players
      @teams = @available_players.group_by(&:team).sort
    end
  end

  # GET /matches/1/edit
  def edit
    @date = @match.start_time
    @absent_players = Absence.where("absent_from <= ? AND absent_until >= ?", @date, @date).map(&:player)
    absent_players_ids = @absent_players.map(&:id) || []
    @available_players = absent_players_ids == [] ? Player.all : Player.where("id NOT IN (?)", absent_players_ids)
    @selected_players = @match.players
    @teams = @available_players.group_by(&:team).sort
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:start_time, :team, :against, :venue, :competition, :score_for, :score_against, :player_ids => [])
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<html class="container col-lg-12">
  
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </head>
  <body>
  
    <% if @match.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

        <ul>
          <% @match.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <% if !@date %>
      <ly>
        <%= form_tag(request.path, :method => :get) do %>
          <div class="field", align = "center">
            <%#= f.collection_select :against, Match.all ,:against, :team, include_blank: true %>
            <l><%= label_tag :start_time %>: </l><br>
            <%= datetime_select :start_time, {}, {:class => "form-control"} %>
          </div>
          <br>
          <div class="actions", align = "center">
            <%= button_tag(type: 'submit', class: "btn btn-success") do %>
               Submit
            <% end %>
          <btn><%= link_to 'Back', matches_path, class: "btn btn-success" %></btn>
        </div>
      <% end %>
    </ly>
    
  <% else %>
  
    
  
    <%= form_for(@match) do |f| %>
    <div align = "center">
      <strong>Date:</strong>
      <d><%= @date.strftime("%d/%m/%Y") %></d>
      
      <div style="visibility:hidden">
      <%= f.datetime_select :start_time %>
      </div>
    
      <div class="field">
        <l></l><%= f.label :team%>: </l><br>
        <%= f.select :team,  [['1sts',1],['2nds',2],['3rds', 3],['4ths', 4]] %>
        </div>
        <br>
        
        <div class="field">
          <l><%= f.label :against %>: </l><br>
          <%= f.text_field :against, class: "form-control-small", placeholder: "Against" %>
        </div>
        
        <div class="field">
        <l></l><%= f.label :venue%>: </l><br>
        <%= f.select :venue,  [['Home'],['Away']] %>
        </div>
        <br>c
        <div class="field">
          <l><%= f.label :competition %>: </l><br>
          <%= f.text_field :competition, class: "form-control-small", placeholder: "Competition" %>
        </div>
        
        <div class="field">
          <l><%= f.label :score_for %>: </l><br>  <!-- label for input field -->
          <%= f.number_field :score_for, class: "form-control-small", placeholder: "Score for"%>  <!-- input field-->
        </div>
        
        <div class="field">
          <l><%= f.label :score_against %>: </l><br>
          <%= f.number_field :score_against, class: "form-control-small", placeholder: "Score against" %>
        </div>
      <br>
      
      <div class="form-group">
                  <div class="panel panel-default">
                    <h4 class="panel-heading text-center"><%= f.label :unavailable_players %></h4>
                    <div class="panel-body">
                      <%= raw @absent_players.map(&:name).join("<br>") %>
                    </div>
                  </div>
              </div>
      
        <div class="form-group">
          <!-- <div class="panel panel-success">
            <h4 class="panel-heading text-center"><%#= f.label :players %></h4>
            <div class="panel-body"> -->
          <%#= f.label :players %><br>
          <strong id="players_selected"><%= @selected_players.count %> players selected to your team</strong>
          <% i = 0 %>
          <% @teams.each do |team, players| %>
            <% if i % 2 == 0 %>
              <div class="row">
            <% end %>
            <div class="">
                <div class="panel panel-default">
                  <h4 class="panel-heading text-center"><%= "Team: #{team}" %></h4>
                  <div class="panel-body">
                  
                    <%= collection_check_boxes(:match, :player_ids, players, :id, :name, checked: @selected_players.map(&:id)) do |b| %>
                      <div class="row">
                        <%= b.label(class: "check_box") do %>
                        <%= b.check_box(class: "check_box") %>    <%= b.object.name %>
                      </div>
                    <% end %>
                    
                <% end %>
                  </div>
                        <% if i % 2 != 0 %>
                      </div>
                    <% end %>
                    <% i += 1 %>
                  </div>
                  
                </div>
                
          <% end %>
      
            <!-- -->
        
      <% end %>
      <div class="actions", align = "center">
        <%= button_tag(type: 'submit', class: "btn btn-success") do %>
           Submit   <!-- label of button -->
        <% end %>
        <btn><%= link_to 'Back', matches_path, class: "btn btn-success" %></btn>    <!-- calling boostrap btn -->
      </div>
    <% end %>
    </div>
    
    </div>
  </body>
</html>

app/views/matches/edit.html.erb
<div class="panel panel-success">
  <h1 class="panel-heading text-center">Editing Match</h1>
    <div class="panel-body">
  
      <%= render 'form' %>
    
    </div>
</div>
<%#= link_to 'Show', @match %> |
<%#= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
    <h1 class="panel-heading text-center">Listing Matches</h1>
      <div class="panel-body">

        <table class = "table table-striped table-bordered">
          <thead>
            <tr>
              <th>Date</th>
              <th>Time</th>
              <th>Team</th>
              <th>Against</th>
              <th>Venue</th>
              <th>Competition</th>
              <th>Score For</th>
              <th>Score Against</th>
              <th>Options</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @matches.each do |match| %>
            <tr class = 'tabel'>
              <td><%= match.start_time.strftime("%d/%m/%Y") %></td>
              <td><%= match.start_time.strftime("%I:%M%p") %></td>
              <td><%= match.team %>'s</td>
              <td><%= match.against %></td>
              <td><%= match.venue %></td>
              <td><%= match.competition %></td>
              <td><%= match.score_for %></td>
              <td><%= match.score_against %></td>
        
              
              
              <td><%= link_to 'View', match, class: "btn btn-default btn-success btn-xs" %></td>
              <% if current_player.captain %>
                <td><%= link_to 'Edit', edit_match_path(match), class: "btn btn-default btn-success btn-xs" %></td>
                <td><%= link_to 'Delete', match, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-success btn-xs" %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>

    </div>
</div>


<br>
<% if current_player.captain %>
  <btn><%= link_to 'New Match', new_match_path, class: "btn btn-default btn-success" %></btn>
<% end %>

app/views/matches/new.html.erb
<div class="panel panel-success">
  <h2 class="panel-heading text-center">New Match</h2>
  <div class="panel-body">
    
  

        <%= render 'form' %>

    </div>
</div>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <h1 class="panel-heading text-center">Viewing Match</h1>
  <div class="panel-body">
    
    <div class="panel panel-default">
      <h1 class="panel-heading text-center">Information</h1>
      <div class="panel-body">
        <p>
          <strong>Date</strong>
          <%= @match.start_time.strftime("%d/%m/%Y") %>
        </p>

        <p>
          <strong>Time</strong>
          <%= @match.start_time.strftime("%I:%M%p") %>
        </p>
    
        <p>
          <strong>Team:</strong>
          <%= @match.team %>
        </p>
    
        <p>
          <strong>Against:</strong>
          <%= @match.against %>
        </p>
        
        <p>
          <strong>Venue:</strong>
          <%= @match.venue %>
        </p>
    
        <p>
          <strong>Competition:</strong>
          <%= @match.competition %>
        </p>
    
        <p>
          <strong>Score for:</strong>
          <%= @match.score_for %>
        </p>
    
        <p>
          <strong>Score against:</strong>
          <%= @match.score_against %>
        </p>
      </div>
    </div>
    <div class="panel panel-default">
      <h1 class="panel-heading text-center">Team</h1>
      <div class="panel-body">
        <p>
          <%= @match.players.map(&:name).join(", ") %>
        </p>
      </div>
    </div>
    <% if current_player.captain %>
      <btn><%= link_to 'Edit', edit_match_path(@match), class: "btn btn-default btn-success" %> </btn>
    <% end %>
    <btn><%= link_to 'Back', matches_path,  class: "btn btn-default btn-success" %> </btn>

  </div>
</div>