config/routes.rb
Rails.application.routes.draw do

  devise_for :players, controllers: {registrations: "registrations"}, skip: [:registrations]
  resources :news
  resources :absences
  #get "players/calendar" => "players#calendar"
  resources :players
  #get "matches/calendar" => "matches#calendar"
  resources :matches
  
  resources :calendar
  
  resources :tables
  
  resources :passwords
  
  root :to => 'calendar#index'
  
  get "/passwords" => "passwords#index"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!-- -->
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Logo Nav - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/logo-nav.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- -->
  <%= csrf_meta_tags %>
  

</head>
    <body class = "container col-lg-12", align = "center">
    <!-- -->
    
        <% if player_signed_in? %>
          <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">
                            <!-- <img src="resized_chief_150x50.jpg" alt=""> -->
                        </a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                             <li>
                              <%= link_to 'Calendar', calendar_index_path  %>
                            </li>
                            <li>
                                <%= link_to 'Matches', matches_path %>
                            </li>
                            <li>
                                <%= link_to 'Absences', absences_path %>
                            </li>
                            <li>
                                <%= link_to 'League Tables', tables_path %>
                            </li>
                            <li>
                                <%= link_to 'Players', players_path %>
                            </li>
                            <li>
                                <%= link_to 'News & Events', news_index_path %>
                            </li>
                            <li>
                                <%= link_to 'Logout', destroy_player_session_path, method: :delete %>
                            </li>
                            
                        </ul>
                    </div>
                    
                    
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
        <% end %> 
    
        <!-- jQuery -->
        <script src="js/jquery.js"></script>
    
        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>
    <!-- -->
    
    <div>
        <%= yield %>
    </div>
    
    
    </body>


</html>